### ISSUE TITLE
Error message when trying out the test

### ISSUE THREAD

**Issue by Thomieh73** [nanoporetech/hammerpede#4]
Hi, I have tried to install the hammerpede tool. I tried out my installation using your test files, and I got an error. 

This is the error output:
```
hp_bootstrap.py -f cDNA_SSP_VNP_full.fas -o test_output -s 0.75 SIRV_E0_pcs109_1k.fq
Traceback (most recent call last):
  File "/cluster/projects/nn9305k/src/miniconda/envs/hammerpede_v0/bin/hp_bootstrap.py", line 64, in <module>
    queries = seq_detect.load_queries(args.f, args.s, None, ALIGN_PARAMS)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/projects/nn9305k/src/miniconda/envs/hammerpede_v0/lib/python3.12/site-packages/hammerpede/seq_detect.py", line 32, in load_queries
    for sr in seu.read_seq_records(in_fas):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/projects/nn9305k/src/miniconda/envs/hammerpede_v0/lib/python3.12/site-packages/hammerpede/seq_utils.py", line 115, in read_seq_records
    handle = open(handle, "rU")
             ^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'
```
I am wondering if this is due to my installation or due to something else.

How I installed the tool

* first created a conda environment called: hammerpede_v0, using a yml file.
The yml file: 
```
name: hammerpede_v0
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - hmmer
 - spoa=4.1.4
 - pip
 - wheel=0.43.0
 ```
I installed the environment, like this:
```
conda env create --prefix /cluster/projects/nn9305k/src/miniconda/envs/hammerpede_vo --file yaml/hammerpede_v0.yml
```
pip and wheel are needed for the environment, otherwise the tool is using the system pip version, and stores the tools from the next step outside if the conda environment.

I then ran the command:
```
pip install git+https://github.com/nanoporetech/hammerpede.git
```

After that I have this:
```
 which hp_bootstrap.py
/cluster/projects/nn9305k/src/miniconda/envs/hammerpede_v0/bin/hp_bootstrap.py

```
and the tool can be called
```
 hp_bootstrap.py -h
usage: hp_bootstrap.py [-h] -f query_fasta -o outdir [-i input_format] [-g aln_params] [-s min_score] input_fastx

Tool train strand-specific profile HMMs of primers from real Nanopore reads.

positional arguments:
  input_fastx      Input read fastq.

options:
  -h, --help       show this help message and exit
  -f query_fasta   Fasta with primer sequences.
  -o outdir        Output directory.
  -i input_format  Input/output format (fastq).
  -g aln_params    Alignment parameters (match, mismatch,gap_open,gap_extend).
  -s min_score     Score cutoff (0.8).
```

Any idea where the error could be coming from?

**Comment by claumer** [comment]
I'm getting this same issue. @cjw85 is this nanopore repo being maintained? This issue has been left standing for over a year.
